easyw/kicad-3d-models-in-freecad

.gitignore, cadquery/FCAD_script_generator/cq_params_qfn.py
Hey easyw,
Seriously cool script you have here.
I've added some DFN parameters and also parameters for a QFN28 part:
Also it seems that some of the rotations were wrong for importing into KiCAD (for some QFN parts)
Here are the new parts I have added:
DFN-6-2x2-p0.65
DFN-8-3x3-p0.50
DFN8-3x3-p0.65
DFN8-2x3-p0.05
DFN8-6x5-p1.27
DFN10-2x3-p0.05
QFN28-6x6-p065
I've checked these against the relevant KiCAD footprints and they all look good.
Cheers
=> Added QFN28 and DFN parameters

cadquery/FCAD_script_generator/cq_params_qfn.py
This PR adds model parameters for the QFN40 (6x6mm 0.5mm pitch) part
e.g. http://www.ti.com/lit/ds/symlink/drv8308.pdf
=> Added QFN40 parameters

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py
Dimensions are from Microchip Packaging Specification ([1]).
[1] http://ww1.microchip.com/downloads/en/PackagingSpec/00000049CH.pdf
Signed-off-by: Sam Protsenko <joe.skb7@gmail.com>
=> ssop: Add QSOP-24 package

cadquery/FCAD_script_generator/Box_Headers/main_generator.py
Running Box_Headers `main_generator.py` gives "missing CadQuery 0.3.0 or later Module!" error message.
Fixed by adding `import FreeCADGui as Gui` (as seen in other generators).
=> Box_Headers: fix incorrect "missing CadQuery" message

cadquery/FCAD_script_generator/4UCON_17809/cq_models/ribbon.py, cadquery/FCAD_script_generator/4UCON_17809/main_generator.py, cadquery/FCAD_script_generator/Molex_54722/cq_models/ribbon.py, cadquery/FCAD_script_generator/Molex_54722/main_generator.py, cadquery/FCAD_script_generator/Molex_55560/cq_models/ribbon.py, cadquery/FCAD_script_generator/Molex_55560/main_generator.py, cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_export.py
Added `sys.path.append('./')` for Windows command line use.  Updated `ribbon.py` helper to latest version (no functional changes).
Models affected:
```
4UCON_17809
Molex_54722
Molex_55560
DPAK
```
=> Fix path for Windows / update ribbon helper

cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_export.py
Author name was not being added to licence in the first (or only) WRL file in a series of models being generated.
=> Fixed problem with author name in WRL file licence

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py
This push consist of 
From http://www.ti.com/lit/ds/symlink/txb0104.pdf
DSBG-12
Texas_Junior_DSBGA-12
From http://datasheets.maximintegrated.com/en/ds/MAX5813-MAX5815.pdf
Maxim-WLP_12
The difference compared to older push is
Junior_DSBGA-12 was renamed into Texas_Junior_DSBGA-12 in accordance to the Maximxxxx guideline 
that manufacture specific footprint should have the company name as prefix
The following will be seperatly pushed to packages3D
DSBGA-12_3x4_1.36x1.86mm_Pitch0.5mm_Dia0.25mm.wrl
DSBGA-12_3x4_1.36x1.86mm_Pitch0.5mm_Dia0.25mm.step
Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5mm.wrl
Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5mm.step
Texas_Junior_DSBGA-12_4x3_2.5x2.0mm_Pitch0.5mm_Dia0.30mm.wrl
Texas_Junior_DSBGA-12_4x3_2.5x2.0mm_Pitch0.5mm_Dia0.30mm.step
=> Renamed Junior_DSGBA into Texas_Junior_DSBGA

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
I spotted a couple of incorrect datasheets used in my earlier PR (https://github.com/easyw/kicad-3d-models-in-freecad/pull/69).  With these fixed, two models needed small changes.
I have updated these models in the related PRs:
https://github.com/KiCad/kicad-library/pull/1305
https://github.com/KiCad/packages3D/pull/64
=> Housings_SON: fix missing EPs, chamfers

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
Added 
Texas_R_PUQFN-N12_2.0x1.7_Pitch0.4mm
Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad
From data sheet http://www.ti.com/lit/ds/symlink/txb0104.pdf
PS
It seems something wrong with model 'DHVQFN14' in cadquery\FCAD_script_generator\QFN_packages
It is not possible to open it up in FreeCad (0.17_pre)
.....bin/FreeCAD.exe ./main_generator.py DHVQFN14
=> Texas_R_PUQFN-N12 and Texas_S-PVQFN-N14

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
"Removed Thermal from Texas_S-PVQFN-N14 and the sizes"
On request from the KiCad library team
=> Removed Thermal from Texas_S-PVQFN-N14 and the sizes

cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325_params.py
Hi
Another change, 
Added pin set 22 and 24, 
Apparently they do not agree on Molex if they make pin 22 and pin24 
This one says it is so
http://www.molex.com/pdm_docs/sd/903250004_sd.pdf
But this one says it does not 
https://www.elfa.se/Web/Downloads/52/02/04355202.pdf
So I added them anyway
=> Added pin 22 and 24

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py
This is a push for aligning 3d model names with already existing footprints
Maxim_WLP-12.kicad_mod
Texas_Junior_DSBGA-48.kicad_mod
Texas_MicroStar_Junior_BGA-12_4x3_2.0x2.5mm_Pitch0.5mm.kicad_mod
The kicad library push (3D models is here
https://github.com/KiCad/kicad-library/pull/1630
the package3D push is here
https://github.com/KiCad/kicad-packages3D/pull/65
the kicad-3d-models-in-freecad is here
https://github.com/easyw/kicad-3d-models-in-freecad/pull/105
=> Name change after foot print review

cadquery/FCAD_script_generator/DIP_packages/main_generator.py
This is a modification of script 
easyw\kicad-3d-models-in-freecad\cadquery/FCAD_script_generator\DIP_packages\main_generator.py
It was used to create the THT variants of the DIP capsule in Housings_DIP.3dshapes
The script is now capable of generating the SMD variants as well
I have deliberately made the shoulder of "smallpads" variants a little smaller o it fits better
/kicad-library/modules/packages3d/Housings_DIP.3dshapes
https://github.com/KiCad/kicad-library/pull/1651
/packages3D/Housings_DIP.3dshape
https://github.com/KiCad/kicad-packages3D/pull/136
kicad-3d-models-in-freecad/cadquery/FCAD_script_generator/DIP_packages
https://github.com/easyw/kicad-3d-models-in-freecad/pull/106
The following is an example of the 3D models
=> Dip 4 w10.16 dip

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
This is push of 3D models of the DFN-6-1EP_3x3mm_Pitch1mm
Used by this one
https://www.silabs.com/documents/public/data-sheets/Si7020-A20.pdf
kicad-library 3D model push
https://github.com/KiCad/kicad-library/pull/1659
KiCad/Housings_DFN_QFN.pretty push
https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/63
KiCad/kicad-packages3D
https://github.com/KiCad/kicad-packages3D/pull/137
easyw/kicad-3d-models-in-freecad
https://github.com/easyw/kicad-3d-models-in-freecad/pull/108
=> Added DFN-6-1EP_3x3mm_Pitch1mm

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_soic.py
This is foot print SO-20_12.8x7.5mm_Pitch1.27mm
It is used by SA605D
https://www.nxp.com/docs/en/data-sheet/SA605.pdf
kicad-library
https://github.com/KiCad/kicad-library/pull/1706
Housings_SOIC.pretty
https://github.com/KiCad/kicad-packages3D/pull/141
kicad-packages3D
https://github.com/KiCad/kicad-packages3D/pull/141
kicad-3d-models-in-freecad
https://github.com/easyw/kicad-3d-models-in-freecad/pull/110
=> Added SO-20_12.8x7.5mm_Pitch1.27mm

cadquery/FCAD_script_generator/Switch_SMD/main_generator_dip.py
Push of 3D models for dip switches
The models is made with python scripts
3D models in kicad-library
https://github.com/KiCad/kicad-library/pull/1775
Modifications of foot prints
https://github.com/KiCad/Buttons_Switches_SMD.pretty/pull/28
3D models in 3D-packages
https://github.com/KiCad/kicad-packages3D/pull/151
3D python script
https://github.com/easyw/kicad-3d-models-in-freecad/pull/116
The following SMB dip switches have 3D models
SW_DIP_x1_W5.08mm_Slide_Copal_CHS-A
SW_DIP_x1_W7.62mm_Slide_Copal_CHS-B
SW_DIP_x1_W8.61mm_Slide_LowProfile
_SPST_EVQPE1
_SPST_REED_CT05-XXXX-G1
_SPST_REED_CT05-XXXX-J1
_SPST_REED_CT10-XXXX-G1
_SPST_REED_CT10-XXXX-G2
_SPST_REED_CT10-XXXX-G4
SW_DIP_x2_W5.08mm_Slide_Copal_CHS-A
SW_DIP_x2_W6.15mm_Slide_Omron_A6H
SW_DIP_x2_W7.62mm_Slide_Copal_CHS-B …
=> Script for 3D models of DIP switches

cadquery/FCAD_script_generator/molex/cq_models/conn_molex_picoblade_53261.py, cadquery/FCAD_script_generator/molex/cq_models/conn_molex_picoblade_53398.py
This corresponds with https://github.com/pointhi/kicad-footprint-generator/pull/94
This is necessary to bring the picoblade footprints in line with KLC F6.2. This needs to be checked for all other connectors as well.
=> Shift picoblade models to match newly shifted footprints

cadquery/FCAD_script_generator/molex/cq_models/conn_molex_picoblade_53261.py
Accidentally placed these in the wrong spot earlier. Fixed now.
=> Correct picoblade 53261 centers

cadquery/FCAD_script_generator/_tools/add_license.py, cadquery/FCAD_script_generator/_tools/cq_cad_tools.py
I added exception handlers to all execptions that simply had a pass statement in them.
(The one in the step license script would have resulted in a null pointer exception or accessed before assigned if it would ever have been triggered.)
Also added warning text if the step file does not exist or if a wrong extension has been discovered. (previously the script told the user via the console that everything is ok even if it failed to add a license.)
`except:` without specifying any exception class would also catch system internal exceptions (exit, and kill). To catch all (user) exceptions, `except Exception:` should be used.
=> Make exceptions more precise and add output where it was missing.

cadquery/FCAD_script_generator/DIP_packages/main_generator.py
It is nosw possible to exclude specific pins when creating the DIP and SMD models
=> Made it possibly to exclude specific pins

cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_config.yaml
Following https://github.com/KiCad/kicad-footprints/pull/482, this changes the 3D model script to use the new name for the LFPAK56 package.
=> Update name of LFPAK56

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_soic.py, cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/main_generator.py
Added SOIC14W parameters from http://www.ti.com/lit/ml/mpds386/mpds386.pdf and fixed a CadQuery not found error on the SOIC generator by following the BGA generator as a template.
=> Add SOIC-14W_7.5x9.0mm_P1.27mm and fix CadQuery not found error

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py
This is a slight modification of the existing SSOP-20 model
parameters, with only two pins removed and the pin width adjusted.
Reference is the Toshiba package documentation at
https://toshiba.semicon-storage.com/us/design-support/package/detail.SSOP18-P-225-0.65.html
The resulting STEP and WRL files have been proposed for addition to the KiCAD library at https://github.com/KiCad/kicad-packages3D/pull/320
=> Add 18-pin variant of SSOP used by Toshiba.

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
Renamed 3D model for Texas_WSON-6_DQK into Texas_DQK on request from FP designer
It is script based
Datasheet: http://www.ti.com/lit/ds/symlink/csd16301q2.pdf
FP push
https://github.com/KiCad/kicad-footprints/pull/999
3D model push
https://github.com/KiCad/kicad-packages3D/pull/416
3D script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/204
=> Renamed Texas_WSON-6_DQK into Texas_DQK

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
Push of a number of missing LGA 3D models
3D model push
https://github.com/KiCad/kicad-packages3D/pull/419
https://github.com/easyw/kicad-3d-models-in-freecad/pull/206
AMS_LGA-10-1EP_2.7x4mm_P0.6mm
LGA-12_2x2mm_P0.5mm
LGA-16_3x3mm_P0.5mm
LGA-16_3x3mm_P0.5mm_LayoutBorder3x5y
LGA-16_4x4mm_P0.65mm_LayoutBorder4x4y
LGA-24L_3x3.5mm_P0.43mm
LGA-28_5.2x3.8mm_P0.5mm
ST_HLGA-10_2.5x2.5mm_P0.6mm_LayoutBorder3x2y
=> Added a number of LGA models

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
This push consist of 103 3D models for DFN/QFN foot prints.
The ordinary cq_paramters.py have been updated by a separate script and all 3D models can be recreated.
The script first find missing 3D models based on the parameter **model** in the foot print file.
Then it exctract the size , pitch and perhaps an epad from the foot print file name.
After that it extract the description and the pads from within the foot pritn file and finally add entries to the cq_paramter file.
It will assume some parameters such as the height and distance from pcb to body, the height is changed in 3 steps depednign of how large the body is.
I guess we have to trust the models and change those which we discover later that are wrong.
Can not expect to review all 103.
There will be a another push for the rest of …
=> Auto geerated 103 models

cadquery/FCAD_script_generator/DIP_packages/FindMissingDIP3DModels.py, cadquery/FCAD_script_generator/DIP_packages/cq_parameters.py
This push consist of 75 3D models for DIP foot prints.
This push also include the script FindMissingDIP3DModels.py that makes the comparison and creation of missing 3D models
The ordinary cq_parameters.py have been updated by a separate script and all 3D models can be recreated.
The script first find missing 3D models based on the parameter **model** in the foot print file.
Then it extract the size , pitch and perhaps an epad from the foot print file name.
After that it extract the description and the pads from within the foot print file and finally add entries to the cq_parameter file.
It will assume some parameters such as the height and distance from pcb to body, the height is changed in 3 steps depending of how large the body is.
I guess we have to trust the models and change those …
=> Added 75 auto generated DIP 3D models

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/FindMissingQFP3DModels.py, cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_qfp.py
This push consist of 23 3D models for QFD  foot prints.
This push also include the script FindMissingQFD3DModels.py that makes the comparison and creation of missing 3D models
The ordinary cq_parameters.py have been updated by a separate script and all 3D models can be recreated.
The script first find missing 3D models based on the parameter **model** in the foot print file.
Then it extract the size , pitch and perhaps an epad from the foot print file name.
After that it extract the description and the pads from within the foot print file and finally add entries to the cq_parameter file.
It will assume some parameters such as the height and distance from pcb to body, the height is changed in 3 steps depending of how large the body is.
I guess we have to trust the models and change those …
=> Added auto generated 23 QFP 3D models

cadquery/FCAD_script_generator/QFN_packages/FindMissingQFN3DModels.py, cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
This push consist of 11 3D models for QFN(LGA)  foot prints.
This push also include the script FindMissingQFN3DModels.py that makes the comparison and creation of missing 3D models
The ordinary cq_parameters.py have been updated by a separate script and all 3D models can be recreated.
The script first find missing 3D models based on the parameter **model** in the foot print file.
Then it extract the size , pitch and perhaps an epad from the foot print file name.
After that it extract the description and the pads from within the foot print file and finally add entries to a separate file which should be merged with cq_parameters.py
It will assume some parameters such as the height and distance from pcb to body, the height is changed in 3 steps depending of how large the body is.
I guess we …
=> Added 11 auto created QFN(LGA) 3D models

cadquery/FCAD_script_generator/BGA_packages/FindMissingBGA3DModels.py, cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py, cadquery/FCAD_script_generator/DIP_packages/FindMissingDIP3DModels.py, cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/FindMissingQFP3DModels.py, cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/FindMissingSOIC3DModels.py, cadquery/FCAD_script_generator/QFN_packages/FindMissingQFN3DModels.py
This push consist of 45 3D models for BGA foot prints.
The ordinary cq_parameters.py have been updated by a separate script and all 3D models can be recreated.
Several of the scripts have been updated so they give more extensive explination and all script look to their structure the same
3D model push
https://github.com/KiCad/kicad-packages3D/pull/454
https://github.com/easyw/kicad-3d-models-in-freecad/pull/221
=> Added missing BGA 3D models

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py
Please consider this addition to the DC to DC converter script to generate the 3D models for the SMT version of the [Artesyn ATA series](https://www.artesyn.com/power/assets/ata_series_ds_01apr2015_79c25814fd.pdf) DC to DC converter.
=> Add Artesyn ATA Series SMT DC to DC converter 3D model script.

cadquery/FCAD_script_generator/Battery/cq_Seiko_MSXXXX.py, cadquery/FCAD_script_generator/Battery/cq_parameters.py, cadquery/FCAD_script_generator/Battery/main_generator.py
When created the 3D model for battery holder Seiko MS621F 
https://www.sii.co.jp/en/me/files/2014/02/file_EXTENDED_PRDCT_SPEC_75_FILE_11.jpg
It seems that the battery circles was off 0.4, earlier origo was at -4.6 but should be 5.0
Foot print push
https://github.com/KiCad/kicad-footprints/pull/1218
3D model push
https://github.com/KiCad/kicad-packages3D/pull/486
https://github.com/easyw/kicad-3d-models-in-freecad/pull/245
=> Added the 3D model for Seiko MS621F

cadquery/FCAD_script_generator/CP_Tantalum_SMD/cq_parameters.py, cadquery/FCAD_script_generator/CP_Tantalum_SMD/main_generator.py
Adding missing tantal SMD capacitors parameters to cq_parameters.py and modified main_generator.py
The following changes have been made to main_generator.py
1. 
If the argument is 'all' the script will try both 'param_nominal' and 'param_max' parameters if they exists, 
that is, if 'all' if it is searching normally for 'param_nominal' and dont find it, it will try 'param_max' and vice versa
2.
It is possible to add 'all' as a second parameter to main_generator.py, like 
`main_generator.py EIA-2012-15 all`
This mean that it will try to use the "other parameter data" if the first dont exist, that is
if it is searching normally for 'param_nominal' and dont find it, it will try 'param_max' and vice versa
3D model push
https://github.com/KiCad/kicad-packages3D/pull/493 …
=> Adding missing tantalum SMD capacitors

cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack.py, cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_cui.py, cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_ledino.py, cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_neutrik.py, cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_qingpu.py, cadquery/FCAD_script_generator/Connector_Audio/cq_common.py, cadquery/FCAD_script_generator/Connector_Audio/main_generator.py
Added a number of 3D models fo the audio jacks
3D model push
https://github.com/KiCad/kicad-packages3D/pull/495
https://github.com/easyw/kicad-3d-models-in-freecad/pull/254
=> Added 3D models of audio jacks

cadquery/FCAD_script_generator/jst/cq_models/conn_jst_eh_params.py, cadquery/FCAD_script_generator/jst/cq_models/conn_jst_xh_params.py
I screwed up it seems. JST does not use leading 0 in the part numbers of these parts.
Additionally: there is no 16 pin variant for the EH connectors.
Library pull request: https://github.com/KiCad/kicad-packages3D/pull/524
=> Fix jst part numbers (remove leading 0)

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
Datasheet used to create this model can be found at:
https://www.ichaus.de/upload/pdf/Package%20dimensions%20DFN_QFN_b2es.pdf
=> Add 10 pin DFN, 4x4mm, 0.65mm pitch, with 2.65x3.05mm exposed pad model.

cadquery/FCAD_script_generator/Battery/battery_casebutton.py
Chnaged Batteryholder_KeyStone_1x2032 on request in
https://github.com/KiCad/kicad-packages3D/pull/480
=> Changed sideopening for BatteryHolder_Keystone_1x2032 to be wider

cadquery/FCAD_script_generator/Converter_ACDC/cq_parameters.py
Original model based on incorrect datasheet interpretation.
Ref: https://github.com/KiCad/kicad-footprints/pull/1439
This should now match the corrected footprint.
=> Correction to MeanWell_IRM-03-xx_THT

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
Added Cq parameters for Texas instruments X2SON-4 (DMR0004A) which is used by DRV5032 Hall-effect sensor.
3D model pull request: KiCad/kicad-packages3D#543
=> Add Texas X2SON-4, DMR0004A

cadquery/FCAD_script_generator/Relay_THT/cq_parameters.py, cadquery/FCAD_script_generator/Relay_THT/main_generator.py
SOURCE PR: easyw/kicad-3d-models-in-freecad#289
FP PR: KiCad/kicad-footprints#1638
SYM PR: KiCad/kicad-symbols#1915
3D PR: https://github.com/KiCad/kicad-packages3D/pull/572
=> Relay_THT: Add a new Panasonic model

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
Push of scripted variant of 
TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm
Instead of hand made model in push
https://github.com/KiCad/kicad-packages3D/pull/570
Data sheet 
https://www.nve.com/Downloads/ab3.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/573
https://github.com/easyw/kicad-3d-models-in-freecad/pull/290
Foot print push
https://github.com/KiCad/kicad-footprints/pull/1647
=> Added 3D model TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm

cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_C26_LF.py, cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_C38_LF.py, cadquery/FCAD_script_generator/Crystal/main_generator.py
This push adds scripts to generate the 3D models of the resonator/crystal C26 and C38 series
3D model push
https://github.com/KiCad/kicad-packages3D/pull/589
https://github.com/easyw/kicad-3d-models-in-freecad/pull/303
=> Scripted 3D models of resonator C26 and C38

cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_peterman_smd.py, cadquery/FCAD_script_generator/Crystal/main_generator.py
Scripted 3D models for 
Crystal_SMD_0603-2Pin_6.0x3.5mm
https://www.petermann-technik.com/fileadmin/documents/datasheets/Quarz-Crystals/SMD-QUARTZ-CRYSTAL-SMD0603-2.pdf
and
Crystal_SMD_0603-4Pin_6.0x3.5mm
https://www.petermann-technik.com/fileadmin/documents/datasheets/Quarz-Crystals/SMD-QUARTZ-CRYSTAL-SMD0603-4.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/590
3D script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/304
=> Added 3D models for crystal 0603 2 and 4 pin

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py, cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_SMD_muRata_CSTx.py
Updating murata naming to "Murata" per https://github.com/KiCad/kicad-footprints/issues/545
kicad-footprints PR: https://github.com/KiCad/kicad-footprints/pull/1681
kicad-packages3D PR: https://github.com/KiCad/kicad-packages3D/pull/595
Currently covers:
- Converter_DCDC
- Crystals
- Some crystals have not yet been generated
and have still been updated.
=> Update murata naming to Murata

cadquery/FCAD_script_generator/LED_SMD/cq_parameters.yaml
Added script based 3D model for  LED_Inolux_IN-PI554FCH_PLCC4_5.0x5.0mm_P3.2mm
Datasheet
http://www.inolux-corp.com/datasheet/SMDLED/Addressable%20LED/IN-PI554FCH_v2.3.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/596
https://github.com/easyw/kicad-3d-models-in-freecad/pull/310
=> Added 3D model for IN-PI554FCH_PLCC4

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py, cadquery/FCAD_script_generator/QFN_packages/main_generator.py
In case of complex pin shapes, it's now possible to add the `custom` pin shape and specify the differents pins shapes relatively to the center of the package.
Example for a `DFN-4` package: https://github.com/maximeborges/kicad-3d-models-in-freecad/commit/a68d78d343ed9624921e3f6543538770535e5409
The 4 pins are defined using the `pin_shapes` optional field with the `ps` field set to `custom`.
The exposed pad is still defined using the `epad` field.
=> Add support for custom pin shapes

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
This is 3D package for PR: https://github.com/pointhi/kicad-footprint-generator/pull/452
It matches the OnSemi Case 506AQ, already included with name DFN-8-1EP_2x2mm_Pitch0.5mm
=> Copy data from DFN-8-1EP_2x2mm_Pitch0.5mm to DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm (name change only)

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py
FP was renamed from SOP-4_4.4x2.8mm_P1.27mm.
See https://github.com/KiCad/kicad-packages3D/pull/649
http://www.vishay.com/docs/83510/tcmt1100.pdf#page=7
=> Fix SOP-4_4.4x2.6mm_P1.27mm

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_tssop.py, cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/create_model-all-TSSOP.bat, cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/main_generator.py
This is part of the addition of JEDEC MO-153 specified footprints.
I have not moved the other TSSOP footprints out of the other definition files yet. I am happy to do that in a separate commit or pull request. Just let me know. I did not want to make the change too big. :)
=> Added the missing JEDEC TSSOP 3d models.

cadquery/FCAD_script_generator/Relay_THT/cq_parameters.py
Follow up of https://github.com/easyw/kicad-3d-models-in-freecad/pull/289
Naming convention in https://github.com/KiCad/kicad-footprints/pull/1638
=> Update relay model naming to follow KLC

cadquery/FCAD_script_generator/DIP_parts/main_generator.py
slash not working in linux:
```
import exportPartToVRML as expVRML
No module named 'exportPartToVRML'
```
=> error when importing in linux otherwise

cadquery/FCAD_script_generator/QFN_packages/main_generator.py
Added check so main generator won't fail in case A1 is zero.
Fix to issue:
https://github.com/easyw/kicad-3d-models-in-freecad/issues/357
=> Check if A1 is zero (main_generator will fail), and set it to 0.02

cadquery/FCAD_script_generator/L_Chip_SMD/cq_parameters.yaml
KiCAD ships with the L_1008 inductor footprint which misses a model. So I'm adding it.
=> Add L_1008 inductor

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
The corresponding footprint was renamed in https://github.com/KiCad/kicad-footprints/pull/1708
so it no longer exists.
Old 3D models were removed in https://github.com/KiCad/kicad-packages3D/pull/715
and it was suggested to remove it from these scripts too.
The replacement scripted data was contributed in https://github.com/easyw/kicad-3d-models-in-freecad/pull/317
The replacement 3D models are being contributed in
https://github.com/KiCad/kicad-packages3D/pull/606
Thanks!
=> Remove UDFN-4_1x1mm_P0.65mm

cadquery/FCAD_script_generator/Connector_FFC-FPC/main_generator.py, cadquery/FCAD_script_generator/jst/main_generator.py, cadquery/FCAD_script_generator/molex/cq_models/conn_molex_kk_5273.py, cadquery/FCAD_script_generator/molex/cq_models/conn_molex_kk_6410.py, cadquery/FCAD_script_generator/molex/launch-cq-molex.sh, cadquery/FCAD_script_generator/molex/main_generator.py
I wanted too add some 3D models for the KK-396 Molex series
I started by the most 'easy' for me, small SPOX series 5273 because there is no grooves, notches, pegs, etc etc on them.
They can temporarily be used for any KK-396 vertical.
I will add the corresponding footprints (meanwhile the 41791 series is usable)
I will try to add 3D models for series 41791 too
Then the right angled variations
So now (if this is accepted), this provides an acceptable model for the series 41791 if generated with alternate mpn_format string.
=> Add KK-396 Molex series 5273 3dmodels

cadquery/FCAD_script_generator/molex/main_generator.py
Use syntax for python >= 3.4
and cosmetic string fix
I'm not a python specialist. Using v3.6.10 on Opensuse.
=> reload not found

cadquery/FCAD_script_generator/Connector_PinHeader/launch-cq-Connector_PinHeader, cadquery/FCAD_script_generator/Connector_PinHeader/launch-cq-Connector_PinHeader.sh, cadquery/FCAD_script_generator/Connector_PinHeader/main_generator.py
I wanted to check why my connectors are all "white".
So, I took this generator and found it not python3 friendly.
Now it is, eg generates the pin headers and they are colored.
Maybe you can save me lot of searches on why I don't have colors on my connectors...
(this is after destroying all the previous repo and mess of PR+commit, now
master only, no more branches shitty things)
=> Py2 to Py3 for connectors pin headers

cadquery/FCAD_script_generator/Connector_Wuerth_WR-PHD/wuerth_wr_phd_bottom_entry.py, cadquery/FCAD_script_generator/Connector_Wuerth_WR-PHD/wuerth_wr_phd_bottom_entry.yaml
Add WR-PHD Bottom Entry series, see https://github.com/KiCad/kicad-packages3D/pull/728
=> Connector Wuerth: Add WR-PHD Bottom Entry series

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py
- Renamed the 3D model because it is SMT instead of THT.
[NXE2 Datasheet](https://www.murata.com/products/productdata/8807031898142/kdc-nxe2.pdf#page=9)
This is related to:
[Symbol PR](https://github.com/KiCad/kicad-symbols/pull/2973)
[Footprint PR](https://github.com/KiCad/kicad-footprints/pull/2463)
[3D package PR](https://github.com/KiCad/kicad-packages3D/pull/729)
[3D generator PR](https://github.com/easyw/kicad-3d-models-in-freecad/pull/395)
[Issue](https://github.com/KiCad/kicad-packages3D/issues/727)
=> Changed NXE2 3D model name

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py
Datasheet:
* Realtek RTD1296 https://download.banana-pi.dev/d/3ebbfa04265d4dddb81b/files/?p=%2FDocuments%2FBPI-W2%2F00007316-RTD1296DB_DC_PB_Datasheet_1.6_106005.pdf
* Rockchip RK3288 https://datasheet.lcsc.com/szlcsc/Rockchip-RK3288_C191247.pdf
Screenshot:
Package dimensions from the RTD1296 data sheet on page 7:
Package dimensions from the RK3288 data sheet on page 25:
=> Add TFBGA-636_19.0x19.0mm_Layout28x28_P0.65mm

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py, cadquery/FCAD_script_generator/Converter_DCDC/launch-cq.sh, cadquery/FCAD_script_generator/Converter_DCDC/main_generator.py
Hello Easy
This PR seems big but not really. It merrily makes a single list for the converters and a single main_generator.py
The produced files are still sorted in two directories, no change for that.
They are the same generators but ACDC was not updated same as DCDC
Now a single generator.py to maintain
Single list of converters
And always two DCDC.3dshapes & ACDC.3dshapes output directories.
Note the SMD PAD generator is strange.
I also added a call to rungeometryCheck,
erase the unneeded .FCStd file
I notice ~12 missing converters than probably can be defined here.
Todo: rename this directory to Converters_ACDC_DCDC and erase
Converters_ACDC
=> Fusion of ACDC & DCDC generators

cadquery/FCAD_script_generator/Resistor_THT/cq_parameters.py, cadquery/FCAD_script_generator/Resistor_THT/create_model.sh, cadquery/FCAD_script_generator/Resistor_THT/main_generator.py
to run python3
to adopt recent change (same script as Converter DCDC)
cq_parameters:
moved the color info in each variant
changed color of SIP resistor to Red
added two sizes for the power vishay CPCC serie: CPC10 CPCC1A
Can't tell if previous CPCC10 was an error (pitch=7.37 ??) it is no more
in the PDF
Remove lot of eol spaces character
Suggestion: use green body for power round resistor, Sfernice like.
adding vishay CPCC  CPC10 CPCC1A 3dimages was the primary goal
=> Convert THT resistor script

cadquery/FCAD_script_generator/Converter_DCDC/main_generator.py, cadquery/FCAD_script_generator/Resistor_THT/main_generator.py
Apparently some python3 version need the current directory added as
search path for module.
Make the comments similar to the DCDC_converter script (it was the model
I used to fix the Resistor script
=> Add scriptpath

cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/README.md, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_base_model.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_base_tact_switches.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_cuk_kmr2x.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_cuk_pts125sx.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_cuk_pts810x.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_parameters.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_ultra_small_tact_switch.py, cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/main_generator.py
Following files will be added:
On branch mr_Button_Switch_Tactile_SMD_THT
Changes to be committed:
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/README.md
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_base_model.py
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_base_tact_switches.py
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_cuk_kmr2x.py
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_cuk_pts125sx.py
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_cuk_pts810x.py
new file:   cadquery/FCAD_script_generator/Button_Switch_Tactile_SMD_THT/cq_parameters.py
new file: …
=> Added  script files for generating 3D models of tactile buttons

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py, cadquery/FCAD_script_generator/STEP_add_license.py, cadquery/cq-ex2.FCMacro
PR to add the USON14 package ([https://www.ti.com/lit/ds/symlink/tpd1e05u06.pdf](https://www.ti.com/lit/ds/symlink/tpd1e05u06.pdf) for reference).
I also added a Linux path to the STEP_add_license.py file, as well as fixed an error with cq-ex2.FCMacro where Draft.scale() doesn't have a scale nor a legacy keyword ([https://wiki.freecadweb.org/Draft_API](https://wiki.freecadweb.org/Draft_API)). Also un-indented *USON-10_2.5x1.0mm_Pitch0.5mm': Params( # ...* to match the rest of the other entries.
=> Added USON-14 and some fixes.
