easyw/kicad-3d-models-in-freecad

cadquery/FCAD_script_generator/cq_params_qfn.py

Hey @easyw I have added parameters for the aforementioned package
(Please ignore the silkscreen under the pads, I'm not done laying out this board :p )

Added parameters for LGA16-3x3mm

---

cadquery/FCAD_script_generator/cq_cad_tools.py
cadquery/FCAD_script_generator/make_box_headers.py

Hey @easyw 
I have created a simple script for generating generic box-headers
Cheers

Added script to generate 2.54mm pitch dual-row box headers

---

cadquery/FCAD_script_generator/cq_cad_tools.py
cadquery/FCAD_script_generator/cq_params_qfn.py
cadquery/FCAD_script_generator/make_qfn_export_fc.py
exportVRMLwColors/exportPartToVRML.py
exportVRMLwColors/shaderColors.py

Works under Windows 8.1.
Tested under FreeCAD 0.15 and CadQuery 0.3.0
Not pretty but you should get the idea how it could be done.

Qfn with new export

---

cadquery/FCAD_script_generator/cq_models/conn_jst_eh_models.py
cadquery/FCAD_script_generator/cq_models/conn_molex_53261.py
cadquery/FCAD_script_generator/cq_models/conn_molex_53398.py
cadquery/FCAD_script_generator/cq_models/conn_phoenix_mc.py
cadquery/FCAD_script_generator/cq_models/conn_phoenix_mstb.py
cadquery/FCAD_script_generator/cq_models/conn_phoenix_mstb_params.py
cadquery/FCAD_script_generator/export_conn_jst_eh.py
cadquery/FCAD_script_generator/export_conn_molex.py
cadquery/FCAD_script_generator/export_conn_phoenix.py

Fix of molex connector file names
added JST EH Series
added option to generate Phoenix connectors with plug

Added JST-EH, better phoenix models, fixed naming of molex connectors

---

cadquery/FCAD_script_generator/cq_params_chip_cap.py
cadquery/FCAD_script_generator/cq_params_radial_smd_cap.py
cadquery/FCAD_script_generator/make_capacitors_export_fc.py
cadquery/FCAD_script_generator/make_radial_smd_export_fc.py

added support for dots in modelname
added parameters for generating up to date kicad compatible models

added VRML properties to Radial SMD caps script

---

cadquery/FCAD_script_generator/4UCON_17809/main_generator.py
cadquery/FCAD_script_generator/Molex_54722/main_generator.py
cadquery/FCAD_script_generator/Molex_55560/main_generator.py
cadquery/FCAD_script_generator/Molex_6410/main_generator.py

Updating `main_generator.py` with latest requirements check code as discussed here: https://github.com/easyw/kicad-3d-models-in-freecad/issues/45#issuecomment-296386466

Updating requirements check code

---

cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/README.md
cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/TO-220-7Lead_TabPin8.py
cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/ribbon.py

Created `TO_SOT_Packages_SMD_custom` folder and `README.md` file.
Added CadQuery script and supporting module.
https://github.com/KiCad/kicad-library/pull/1193
https://github.com/KiCad/packages3D/pull/40

Add script for TO-220-7Lead_TabPin8

---

cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_export.py
cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_factory.py

No functional changes, just some refactoring, removing unused code, fixed some gaps in copyright credits.
Improved structure of model dict passed from factory to export program, so `DPAK_factory.py` changed to match.

DPAK_export.py: tidied up code

---

cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_config.yaml
cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_factory.py

Main PR: https://github.com/KiCad/kicad-library/pull/1242

Update DPAK script to add models for HSOF-8-1 and SOT-669

---

cadquery/FCAD_script_generator/Molex_5569/conn_molex_5569.py
cadquery/FCAD_script_generator/Molex_5569/cq_parameters.py
cadquery/FCAD_script_generator/Molex_5569/main_generator.py

First attempt with cadquery and Python. A few details still missing (like small ribs on the side, and splits in pegs, and contact cavities all square), but still could be useful.

Molex 5569 series (Mini-Fit Jr Angled with pegs)

---

cadquery/FCAD_script_generator/capacitors_radial_THT/cq_parameters.py
cadquery/FCAD_script_generator/capacitors_radial_THT/main_generator.py

added parameters and a few fixes :)

---

cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_config.yaml
cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom/DPAK_factory.py

**Main PR**
https://github.com/KiCad/kicad-library/pull/1250

Updating script to add SOT-89-3

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_soic.py

Added the SO-6L model to the SOIC directory

Added the SO-6L model in the SOIC directory

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

Added the maxim specific model WLP-12
http://pdfserv.maximintegrated.com/package_dwgs/21-0009.PDF
Model W121B2+1

Added model Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5 in the BGA directory

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Created 12 models required for Housings_SON by adding parameters to the existing QFN script.
**Main PR**
*link TBA*
**Related PRs**
https://github.com/KiCad/Housings_SON.pretty/pull/7

Housings_SON: added parameters to QFN script

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Based on feedback on previous PR (https://github.com/KiCad/kicad-library/pull/1303), improvements to some of the SON models.  
Main PR:
https://github.com/KiCad/kicad-library/pull/1305

Housings_SON: improvements to models

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

After trying to add the corresponding foot print to Kicad some changes needed to be done

Dsbga 12 bga microstar junior

---

cadquery/FCAD_script_generator/DIP_packages/main_generator.py

Package used by UM61512AK SRAM and may be others components.

Add DIP-32_W7.62mm support

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/README.adoc
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/cq_parameters.py
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/create_model-all.bat
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/create_model-example.bat
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/create_model.bat
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/create_model.sh
cadquery/FCAD_script_generator/capacitors_nonpolarized_axial_THT/main_generator.py

added script and parameters for C_Axial_THT caps (porting of Jans)

---

cadquery/FCAD_script_generator/CP_Tantalum_THT/README.adoc
cadquery/FCAD_script_generator/CP_Tantalum_THT/cq_parameters.py
cadquery/FCAD_script_generator/CP_Tantalum_THT/create_model-all.bat
cadquery/FCAD_script_generator/CP_Tantalum_THT/create_model-example.bat
cadquery/FCAD_script_generator/CP_Tantalum_THT/create_model.bat
cadquery/FCAD_script_generator/CP_Tantalum_THT/create_model.sh
cadquery/FCAD_script_generator/CP_Tantalum_THT/main_generator.py

for some reason CP_Radial_Tantal_D9.0mm_Px.xxmm crashes in FC0.16 but works fine in FC0.17.. its driving me mad! can you please have a look at it @easyw?

added CP_Tantal_generator

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

Added Texas_Junior_DSBGA-48
http://www.ti.com/lit/ml/mpbg309/mpbg309.pdf
Used by TSC2046, see https://github.com/KiCad/kicad-library/pull/1491

Added Texas_Junior_DSBGA-48

---

cadquery/FCAD_script_generator/Molex_90325/README.adoc
cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325.py
cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325_params.py
cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_global_params.py
cadquery/FCAD_script_generator/Molex_90325/create_model.bat
cadquery/FCAD_script_generator/Molex_90325/create_model.sh
cadquery/FCAD_script_generator/Molex_90325/main_generator.py

Here is scripts to generate the Molex picoflex contact, serie 90325
http://www.molex.com/pdm_docs/sd/903250004_sd.pdf
(This is a better document but I can not find it on Molex home page 
https://www.elfa.se/Web/Downloads/52/02/04355202.pdf)

Molex 90325

---

cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325.py
cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325_params.py

Modification of push 
https://github.com/easyw/kicad-3d-models-in-freecad/pull/95
The metal pins are little smaller

Molex 90325 2

---

cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325.py
cadquery/FCAD_script_generator/Molex_90325/cq_models/conn_molex_90325_params.py

Forgot to compensate for KiCad's, uhhhmmm "unique", coordinate system where the y value decrease above the X-axis

Molex 90325 5

---

cadquery/FCAD_script_generator/Molex_90814/README.adoc
cadquery/FCAD_script_generator/Molex_90814/cq_models/conn_molex_90814.py
cadquery/FCAD_script_generator/Molex_90814/cq_models/conn_molex_90814_params.py
cadquery/FCAD_script_generator/Molex_90814/cq_models/conn_molex_global_params.py
cadquery/FCAD_script_generator/Molex_90814/create_model.bat
cadquery/FCAD_script_generator/Molex_90814/create_model.sh
cadquery/FCAD_script_generator/Molex_90814/main_generator.py

Molex Picoflex PF-50 90814 series script creator
Pins 4 to 26 in step of 2.
http://www.molex.com/pdm_docs/sd/908140004_sd.pdf
The 3D models are created by easyw/kicad-3d-models-in-freecad script, see push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/99

Molex 90814

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_sot.py

Added SOT23-W
http://www.allegromicro.com/~/media/Files/Datasheets/A112x-Datasheet.ashx?la=en&hash=7BC461E058CC246E0BAB62433B2F1ECA104CA9D3

Added SOT-23W

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

MFSOP6-4
https://toshiba.semicon-storage.com/ap-en/design-support/package/detail.4pin%20MFSOP6.html
MFSOP6-5
https://toshiba.semicon-storage.com/ap-en/design-support/package/detail.5pin%20MFSOP6.html
kicad-library
https://github.com/KiCad/kicad-library/pull/1553

Added MFSOP6

---

cadquery/FCAD_script_generator/DIP_packages/main_generator.py

Renamed according to 
https://github.com/KiCad/Housings_DIP.pretty/pull/15

Renamed SMD variants

---

cadquery/FCAD_script_generator/Box_Headers/main_generator.py

Several changes:
(1) Realign IDC connectors as updated per https://github.com/KiCad/Connectors_IDC.pretty/pull/3
(2) Add angled connector 3D model outputs

IDC Connector Improvements

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

VSSOP-8 3.0x3.0 mm
http://www.ti.com/lit/ds/symlink/lm75b.pdf
kicad library 3D model
https://github.com/KiCad/kicad-library/pull/1743
kicad pretty
https://github.com/KiCad/Housings_SSOP.pretty/pull/50
kicad package 3D
https://github.com/KiCad/kicad-packages3D/pull/144
kicad 3D script
https://github.com/easyw/kicad-3d-models-in-freecad/pull/114

Added VSSOP-8_3.0x3.0mm_Pitch0.65mm

---

cadquery/FCAD_script_generator/Resistors_THT/README.adoc
cadquery/FCAD_script_generator/Resistors_THT/cq_parameters.py
cadquery/FCAD_script_generator/Resistors_THT/create_model-all.bat
cadquery/FCAD_script_generator/Resistors_THT/create_model-example.bat
cadquery/FCAD_script_generator/Resistors_THT/create_model.bat
cadquery/FCAD_script_generator/Resistors_THT/create_model.sh
cadquery/FCAD_script_generator/Resistors_THT/main_generator.py
cadquery/FCAD_script_generator/Resistors_THT/todo.md

Add resistors_tht package script.
Models submitted to repository with [kicad-packages3D/pull/152](https://github.com/KiCad/kicad-packages3D/pull/152).
Based on existing scripts.

Resistors THT

---

cadquery/FCAD_script_generator/DIP_parts/README.adoc
cadquery/FCAD_script_generator/DIP_parts/cq_base_model.py
cadquery/FCAD_script_generator/DIP_parts/cq_model_piano_switch.py
cadquery/FCAD_script_generator/DIP_parts/cq_model_pin_switch.py
cadquery/FCAD_script_generator/DIP_parts/cq_model_smd_switch.py
cadquery/FCAD_script_generator/DIP_parts/cq_model_smd_switch_copal.py
cadquery/FCAD_script_generator/DIP_parts/cq_model_smd_switch_omron_a6h.py
cadquery/FCAD_script_generator/DIP_parts/cq_model_socket_turned_pin.py
cadquery/FCAD_script_generator/DIP_parts/cq_parameters.py
cadquery/FCAD_script_generator/DIP_parts/create_model-all.bat
cadquery/FCAD_script_generator/DIP_parts/create_model-example.bat
cadquery/FCAD_script_generator/DIP_parts/create_model.bat
cadquery/FCAD_script_generator/DIP_parts/create_model.sh
cadquery/FCAD_script_generator/DIP_parts/list_model-all.bat
cadquery/FCAD_script_generator/DIP_parts/main_generator.py
cadquery/FCAD_script_generator/_tools/add_license.py

Turned pin sockets and THT/SMD switches - for review
Newbie at this so need to learn about the level of detail required for models++
I have made my scripts class based and are using inheritance as this feels more natural to me, but as I am a newbie to pyton programming too so there may be room for further improvements.
Example part:

Assorted DIP parts

---

cadquery/FCAD_script_generator/Box_Headers/main_generator.py

See title.
This is already ready to merge.
Packages 3d PR: https://github.com/KiCad/kicad-packages3D/pull/196

Fix naming for box header generator. Add geometry check

---

cadquery/FCAD_script_generator/BGA_packages/.gitignore
cadquery/FCAD_script_generator/BGA_packages/main_generator.py
cadquery/FCAD_script_generator/Box_Headers/.gitignore
cadquery/FCAD_script_generator/Box_Headers/main_generator.py
cadquery/FCAD_script_generator/CP_Tantalum_SMD/.gitignore
cadquery/FCAD_script_generator/CP_Tantalum_SMD/cq_parameters.py
cadquery/FCAD_script_generator/CP_Tantalum_SMD/main_generator.py
cadquery/FCAD_script_generator/CP_Tantalum_THT/.gitignore
cadquery/FCAD_script_generator/CP_Tantalum_THT/main_generator.py
cadquery/FCAD_script_generator/_tools/add_license.py
cadquery/FCAD_script_generator/_tools/cqToolsExceptions.py
cadquery/FCAD_script_generator/_tools/cq_cad_tools.py
cadquery/FCAD_script_generator/_tools/exportPartToVRML.py
cadquery/FCAD_script_generator/jst/main_generator.py
cadquery/FCAD_script_generator/molex/main_generator.py
cadquery/FCAD_script_generator/phoenix_contact/.gitignore
cadquery/FCAD_script_generator/phoenix_contact/main_generator.py

**To not merge yet**
This pull request will add geometry check to tantal caps.
I will also update the naming convention stuff and make it easier to change the naming convention.
I also cleaned up my other generators by moving the geometry check stuff into cq_tools
And i moved the output dir to _3dmodels

Tantal add geometry check plus new names

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

WSON-8-1EP_3x3mm_P0.5mm_EP1.6x2.0mm
Datasheet: http://www.ti.com/lit/ml/mpds403/mpds403.pdf

Added WSON-8-1EP_3x3mm_P0.5mm_EP1.6x2.0mm

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

SSOP-8_3.95x5.21x3.27mm_P1.27mm
Datasheet: http://www.cel.com/pdf/datasheets/ps8802.pdf

Add SSOP-8_3.95x5.21x3.27mm_Pitch1.27mm

---

cadquery/FCAD_script_generator/Resistor_SMD/cq_parameters.yaml

https://www.seielect.com/catalog/SEI-CSS_cssh.PDF

Add Stackpole CSS/CSSH resistors

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

As merged in https://github.com/KiCad/kicad-packages3D/pull/297#issuecomment-385801535.

Add WQFN-20-1EP_4.5x2.5mm_Pitch0.5mm_EP2.9x1.0mm

---

cadquery/FCAD_script_generator/Converter_ACDC/main_generator_Converter_ACDC.py
cadquery/FCAD_script_generator/Converter_DCDC/main_generator_Converter_DCDC.py

Hi
Finally I was able to push, 
This fix include some name changes and bened pins are smothly shaped

Split acdc dcdc into acdc and dcdc 3

---

cadquery/FCAD_script_generator/Flat_Pin_packages/cq_parameters_sot.py

SOT-553 without an excluded pin.

Add SOT-563

---

cadquery/FCAD_script_generator/Converter_DCDC/main_generator_Converter_DCDC.py

See https://github.com/KiCad/kicad-footprints/pull/688  and https://github.com/KiCad/kicad-packages3D/pull/327 for details.

Fix footprint of RECOM DC/DC adapters.

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Adding WSON-8-1EP_2x2mm_P0.5mm_EP0.9x1.6mm

Adding WSON-8-1EP_2x2mm_P0.5mm_EP0.9x1.6mm

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

Add VSSOP-10_3x3mm_P0.5mm

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_soic.py

ST_MultipowerSO-30
https://www.st.com/resource/en/datasheet/vnh5019a-e.pdf
This is a script based re push of ST_MultipowerSO-30 hand made model
Original push 
https://github.com/KiCad/kicad-packages3D/pull/363#issuecomment-419178488
3D model push
https://github.com/KiCad/kicad-packages3D/pull/393
Script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/191

Added ST_MultiPowerSO-30

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

correct VSSOP-10 body size from 4.6 to 4.9

correct VSSOP-10 body size from 4.6 to 4.9

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

[3D package PR](https://github.com/KiCad/kicad-packages3D/pull/399)

Adding QFN-76-1EP_9x9mm_P0.4mm_EP3.8x3.8mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

I add VSON 10 3.0x3.0mm package.
Related PR:
https://github.com/KiCad/kicad-packages3D/pull/400
https://github.com/KiCad/kicad-packages3D/pull/401

Add VSON 10 3.0x3.0mm

---

cadquery/FCAD_script_generator/Converter_ACDC/main_generator_Converter_ACDC.py

I've just added a single new part, the Racom RAC04 AC-DC converter.

Added Recom RAC04 part

---

cadquery/FCAD_script_generator/Converter_DCDC/main_generator_Converter_DCDC.py

I also performed some house keeping on this file as it had a lot of trailing whites pace and I changed the utf8 specifier to utf-8 because my editor was complaining about the encoding when saving.

Add model for XP Power JTE series dual output DC to DC converter.

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

3D model for Texas_WSON-6_DQK
It is script based
Datasheet: http://www.ti.com/lit/ds/symlink/csd16301q2.pdf
FP push
https://github.com/KiCad/kicad-footprints/pull/999
3D model push
https://github.com/KiCad/kicad-packages3D/pull/416
3D script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/203

Added Texas_WSON-6_DQK

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

Add BGA-624_25x25_21.0x21.0mm_Pitch0.8mm

---

cadquery/FCAD_script_generator/Converter_DCDC/README.txt
cadquery/FCAD_script_generator/Converter_DCDC/main_generator_Converter_DCDC.py

3D model for push
https://github.com/KiCad/kicad-footprints/pull/1044
Data sheet
https://power.murata.com/data/power/ncl/kdc_ncs1.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/424
3D model is script made
https://github.com/easyw/kicad-3d-models-in-freecad/pull/208

added 3D model for Converter_DCDC_muRata_NCS1SxxxxSC_THT

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

A number of missing BGA 3D models
All are script based
3D model push
https://github.com/KiCad/kicad-packages3D/pull/426
https://github.com/easyw/kicad-3d-models-in-freecad/pull/209
Example of the result

Added a number of misisng BGA 3D models

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

A number of missing BGA 3D models
All are script based
3D model push
https://github.com/KiCad/kicad-packages3D/pull/427
https://github.com/easyw/kicad-3d-models-in-freecad/pull/210
Example of the result

Added 3D BGA models

---

cadquery/FCAD_script_generator/BGA_packages/cq_parameters.py

A number of missing BGA 3D models
All are script based
3D model push
https://github.com/KiCad/kicad-packages3D/pull/428
https://github.com/easyw/kicad-3d-models-in-freecad/pull/211

Added a number of BGA 3D models

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/FindMissingSOIC3DModels.py
cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_soic.py

Modified the Script so a lower t_bs is written to the cq_paramter_soic.py file when the soic is very wide
See 
https://github.com/easyw/kicad-3d-models-in-freecad/issues/215
for more information

Modified paramter file and script generator so it can handle wider soics

---

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py

I finally got this sorted out so here the patch for the 3D model script used to generate the XP Power ISU02 series DC to DC converter module.  Please let me know if there are any issues.

Add XP Power ISU02 series DC to DC converter SMT 3D model.

---

cadquery/FCAD_script_generator/Varistor/FindMissingVaristor3DModels.py
cadquery/FCAD_script_generator/Varistor/README.txt
cadquery/FCAD_script_generator/Varistor/cq_parameters.py
cadquery/FCAD_script_generator/Varistor/main_generator.py

This push consist of parameter file and python scripts for creating varistors
The push also include FindMissingVaristor3DModels.py which can be used to find missing 3D models for varistors.
3D model push
https://github.com/KiCad/kicad-packages3D/pull/463
https://github.com/easyw/kicad-3d-models-in-freecad/pull/226

Added paramter file and scripts for varistors

---

cadquery/FCAD_script_generator/Valves/README.adoc
cadquery/FCAD_script_generator/Valves/cq_parameters.py
cadquery/FCAD_script_generator/Valves/main_generator.py
cadquery/FCAD_script_generator/_tools/shaderColors.py

Added script to build 3D models of valves
I also updated ..../_tools/shaderColors.py with the colours in the kicad_stepup macro that was missing in shaderColors.py.
I did not update ....../exportVRML/shaderColors.py, I am not sure if hat is used or not
for simplicity I choose not to add any "content" inside the valve and i used blue glass to give it some colours.
3D model push
https://github.com/KiCad/kicad-packages3D/pull/466
3D model script
https://github.com/easyw/kicad-3d-models-in-freecad/pull/228

Added scripts to build valves

---

cadquery/FCAD_script_generator/Transformer_THT/cq_parameters.py
cadquery/FCAD_script_generator/Transformer_THT/main_generator.py

cq_paramter file and generator file for a number of transformers
3D model push
https://github.com/KiCad/kicad-packages3D/pull/468
3D model script
https://github.com/easyw/kicad-3d-models-in-freecad/pull/229

Added parametrizied transformer file and generator script

---

cadquery/FCAD_script_generator/Valves/cq_parameters.py
cadquery/FCAD_script_generator/Valves/main_generator.py

New push of the valves, they look like this now
3D model push
https://github.com/KiCad/kicad-packages3D/pull/466

Changed glass to grey and add red inside to glimmer

---

cadquery/FCAD_script_generator/Valves/README.adoc
cadquery/FCAD_script_generator/Valves/cq_parameters.py
cadquery/FCAD_script_generator/Valves/cq_parameters_glim.py
cadquery/FCAD_script_generator/Valves/cq_parameters_socket_belton.py
cadquery/FCAD_script_generator/Valves/cq_parameters_socket_generic.py
cadquery/FCAD_script_generator/Valves/cq_parameters_socket_tag.py
cadquery/FCAD_script_generator/Valves/cq_parameters_tube_CK6418.py
cadquery/FCAD_script_generator/Valves/cq_parameters_tube_generic.py
cadquery/FCAD_script_generator/Valves/main_generator.py

Overhaul of the valve foot prints
All foot prints are script made (except CK6418)
All 3D models are script made
The models and foot print does not replace existing valve foot prints.
Removal of old foot prints will be done with a later push of thesymbols
Foot print push
https://github.com/KiCad/kicad-footprints/pull/1111
Foot print script push
https://github.com/pointhi/kicad-footprint-generator/pull/226
3D model push
https://github.com/KiCad/kicad-packages3D/pull/466
3D model scripts
https://github.com/easyw/kicad-3d-models-in-freecad/pull/234

Scripts that create 3D models of valve tubes and sockets

---

cadquery/FCAD_script_generator/Altech/cq_parameters.py
cadquery/FCAD_script_generator/Altech/main_generator.py

This the push of Altech AK300 serie
http://www.altechcorp.com/PDFS/PCBMETRC.PDF
All foot prints and 3D models are script made
Foot print push
https://github.com/KiCad/kicad-footprints/pull/1155
Foot print script push 
https://github.com/pointhi/kicad-footprint-generator/pull/236
3D model push
https://github.com/KiCad/kicad-packages3D/pull/478
https://github.com/easyw/kicad-3d-models-in-freecad/pull/242
Parameter file foot prints
```
AK300:
description: "Altech AK300 serie connector"
datasheet: "http://www.altechcorp.com/PDFS/PCBMETRC.PDF"
tags: "Altech AK300 serie connector"
manufacture: 'Altech' # Model name
serie: 'AK300'        # Model name
W: 12.5               # Package width
H: 12.5               # Package height
WD: 6.5               # > Y distance form pin …
```

Added Altech AK300 serie

---

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py
cadquery/FCAD_script_generator/Converter_DCDC/main_generator.py

cannot generate the 3D model myself, please check.

scripts of SF_IA, SF_IH, SF_ITX and SF_ITQ series of XP_POWER DCDC converters

---

cadquery/FCAD_script_generator/Battery/battery_caseBX0036.py
cadquery/FCAD_script_generator/Battery/battery_casebutton.py
cadquery/FCAD_script_generator/Battery/battery_casecylinder.py
cadquery/FCAD_script_generator/Battery/battery_common.py
cadquery/FCAD_script_generator/Battery/battery_contact.py
cadquery/FCAD_script_generator/Battery/battery_pins.py
cadquery/FCAD_script_generator/Battery/cq_parameters.py
cadquery/FCAD_script_generator/Battery/main_generator.py

Scripted 3D models of the batteryholder
Now, some of the 3D models differ a little from the true 3D model, that is, how they look "inside" 
not dead accurate to the F.Fab line of the foot print etc.
This is due to missing information in the data sheet so both I and the original foot print maker 
had to use our imagination.
The scripts handle 7 different pin configurations and 4 different bodies, 
so these scripts is a beginning.

Added scripted battery holders

---

cadquery/FCAD_script_generator/Battery/cq_Keystone_2993.py
cadquery/FCAD_script_generator/Battery/cq_Seiko_MSXXXX.py
cadquery/FCAD_script_generator/Battery/cq_parameters.py
cadquery/FCAD_script_generator/Battery/main_generator.py

3D model of Keystone 3993 
https://www.keyelco.com/product-pdf.cfm?p=776
3D model push
https://github.com/KiCad/kicad-packages3D/pull/487
https://github.com/easyw/kicad-3d-models-in-freecad/pull/246

Added Keystone 2993 3D model

---

cadquery/FCAD_script_generator/CP_Radial_SMD/cq_parameters.py
cadquery/FCAD_script_generator/CP_Radial_SMD/main_generator.py

Adding 3D models of non polarized bulk SMD capacitors
3D model push 
https://github.com/KiCad/kicad-packages3D/pull/490
https://github.com/easyw/kicad-3d-models-in-freecad/pull/249

Added the non polarized bulk SMD capacitors

---

cadquery/FCAD_script_generator/C_Trimmer/cq_common.py
cadquery/FCAD_script_generator/C_Trimmer/cq_murata.py
cadquery/FCAD_script_generator/C_Trimmer/cq_sprague_goodman.py
cadquery/FCAD_script_generator/C_Trimmer/cq_voltronics.py
cadquery/FCAD_script_generator/C_Trimmer/main_generator.py

Adding 3D models for capacitance trimmers
They are all scripted
C_Trimmer_Sprague-Goodman_SGC3
http://media.wix.com/ugd/d86717_38d9821e12823a7aa9cef38c6c2a73cc.pdf
Voltronics
http://www.knowlescapacitors.com/File%20Library/Voltronics/English/GlobalNavigation/Products/Trimmer%20Capacitors/CerChipTrimCap.pdf
Murata
https://www.murata.com/~/media/webrenewal/support/library/catalog/products/capacitor/trimmer/t13e.ashx?la=en-gb
3D models push
https://github.com/KiCad/kicad-packages3D/pull/491
3D model scripts push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/250

Added 3D models of the capacitance trimmers

---

cadquery/FCAD_script_generator/Altech/cq_parameters.py
cadquery/FCAD_script_generator/Altech/main_generator.py

On request in thread
https://github.com/KiCad/kicad-footprints/pull/1155
The target directory and file ending have changed for AK300 terminal block serie

Changed the file name ending of the AK300 terminal block serie

---

cadquery/FCAD_script_generator/Filter/cq_common.py
cadquery/FCAD_script_generator/Filter/cq_kyocera.py
cadquery/FCAD_script_generator/Filter/cq_minicircuit.py
cadquery/FCAD_script_generator/Filter/cq_murata.py
cadquery/FCAD_script_generator/Filter/main_generator.py

Scripts for generating all filter 3D models
Filter_1109-5_1.1x0.9mm
https://www.murata.com/~/media/webrenewal/support/library/catalog/products/filter/rf/p73e.ashx?la=en-gb
Filter_1411-5_1.4x1.1mm
https://global.kyocera.com/prdct/electro/product/pdf/sf14_tdlte.pdf
https://ww2.minicircuits.com/case_style/FV1206.pdf
https://ww2.minicircuits.com/case_style/FV1206-1.pdf
https://ww2.minicircuits.com/case_style/FV1206-4.pdf
https://ww2.minicircuits.com/case_style/FV1206-5.pdf
https://ww2.minicircuits.com/case_style/FV1206-6.pdf
https://ww2.minicircuits.com/case_style/FV1206-7.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/509
https://github.com/easyw/kicad-3d-models-in-freecad/pull/262
3D model source push (remove hand made models) …

Added 3D models of filters, murata, minicircuits and kyocera

---

cadquery/FCAD_script_generator/Fuse/cq_bulgin.py
cadquery/FCAD_script_generator/Fuse/cq_common.py
cadquery/FCAD_script_generator/Fuse/cq_keystone.py
cadquery/FCAD_script_generator/Fuse/cq_littlefuse.py
cadquery/FCAD_script_generator/Fuse/cq_schurter.py
cadquery/FCAD_script_generator/Fuse/cq_tme.py
cadquery/FCAD_script_generator/Fuse/main_generator.py

A number of 3D fuse models
All models are made with script
3D model push
https://github.com/KiCad/kicad-packages3D/pull/511
https://github.com/easyw/kicad-3d-models-in-freecad/pull/263

Added a numner of 3D fuse models

---

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py

and fix IA first pin position and case tolerances of IA IH

remove SIP - DIP from filename

---

cadquery/FCAD_script_generator/Converter_DCDC/main_generator.py

and change default model to build

print error to console when incorrect filename

---

cadquery/FCAD_script_generator/CP_Radial_THT/main_generator.py

Added indication of fracture ontop of the unpolarized capacitors
Related to push
https://github.com/KiCad/kicad-packages3D/pull/494

Added indication of fracture ontop of the unpolarized capacitors

---

cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_neutrik.py

Changed the neutrik connector to 6.35 both hole and filename
Requested in 
https://github.com/KiCad/kicad-packages3D/pull/495
Which originally comes from
https://github.com/KiCad/kicad-footprints/pull/1145

Changed neutrik to 6.35mm hole

---

cadquery/FCAD_script_generator/Varistor/cq_parameters.py
cadquery/FCAD_script_generator/Varistor/main_generator.py

3d PR https://github.com/KiCad/kicad-packages3D/pull/519

Varistor: Add new model

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Add QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm

---

cadquery/FCAD_script_generator/Connector_Coaxial/cq_coaxial_amphenol.py
cadquery/FCAD_script_generator/Connector_Coaxial/cq_coaxial_molex.py
cadquery/FCAD_script_generator/Connector_Coaxial/cq_coaxial_samtec.py
cadquery/FCAD_script_generator/Connector_Coaxial/cq_coaxial_te.py

Updated the coaxial connectors after review
https://github.com/KiCad/kicad-packages3D/pull/496

Updated coaxial connectors after review

---

cadquery/FCAD_script_generator/Conn_Stocko/cq_parameters.yaml
cadquery/FCAD_script_generator/Conn_Stocko/main_generator.py

Hi, this is a script for generating Stocko MKS 3D models.

add Stocko MKS 3D generator script

---

cadquery/FCAD_script_generator/Filter/cq_kyocera.py
cadquery/FCAD_script_generator/Filter/cq_minicircuit.py
cadquery/FCAD_script_generator/Filter/cq_murata.py

Rotated 90 degree on request in https://github.com/KiCad/kicad-packages3D/pull/509

Fixed inside step filename and rotation parameter

---

cadquery/FCAD_script_generator/Package_SIP/cq_SIP_3.py

I add have SIP-9_21.54x3mm_P2.54mm
On request in https://github.com/KiCad/kicad-packages3D/pull/484

Added Added SIP-9_21.54x3mm_P2.54mm

---

cadquery/FCAD_script_generator/Connector_Dsub/cq_dsub.py
cadquery/FCAD_script_generator/Connector_Dsub/main_generator.py

A fix that removes a phantom box in case a 3D model do not have npth pins
on request in 
https://github.com/KiCad/kicad-packages3D/pull/500

Dsub 3 d model 2

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_soic.py
cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/main_generator.py

3D PR: https://github.com/KiCad/kicad-packages3D/pull/569

Add a new SOIC 8 model

---

cadquery/FCAD_script_generator/Relay_THT/README.txt
cadquery/FCAD_script_generator/Relay_THT/cq_parameters.py
cadquery/FCAD_script_generator/Relay_THT/main_generator.py

Push of three transfomers
Initiated be the push 
https://github.com/KiCad/kicad-packages3D/pull/548
Data sheet
http://www.sanyourelay.ca/public/products/pdf/SRD.pdf
The models are scripted
3D model push
https://github.com/KiCad/kicad-packages3D/pull/564
https://github.com/easyw/kicad-3d-models-in-freecad/pull/286

Added scripts for generating transformers

---

cadquery/FCAD_script_generator/phoenix_contact/README_WHY_2_main_generator.md
cadquery/FCAD_script_generator/phoenix_contact/cq_parameters.py
cadquery/FCAD_script_generator/phoenix_contact/main_generator2.py

This is a scripted version of Phoenix terminal block MKDS serie 5.08 mm
https://www.phoenixcontact.com/online/portal/gb/?uri=pxc-oc-itemdetail:pid=1715802&library=gben&pcck=P-11-01-05&tab=1&selectedCategory=ALL
On request by  easyw in push
https://github.com/KiCad/kicad-packages3D/pull/567
Pins 2 to 16 is generated with script
3D model push
https://github.com/KiCad/kicad-packages3D/pull/571
https://github.com/easyw/kicad-3d-models-in-freecad/pull/288

Added Phoenix terminal block serie MKDS, 5.08mm Horizontal

---

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py

Source file for Murata MGJ2DxxxxxxSC DCDC Converter
PR is related to https://github.com/KiCad/kicad-packages3D/pull/574#issuecomment-504747633

Add Parameter for MGJ2DxxxxxxSC_THT DCDC Converter

---

cadquery/FCAD_script_generator/Converter_ACDC/main_generator.py

Scripts can be run with FreeCAD 0.18

Improve Python 3 compatibility

---

cadquery/FCAD_script_generator/LED_SMD/cq_parameters.yaml
cadquery/FCAD_script_generator/LED_SMD/main_generator.py

Added 3D model of LED_RGB_5050-6
See push
https://github.com/KiCad/kicad-packages3D/pull/581

Added 3D model LED_RGB_5050-6

---

cadquery/FCAD_script_generator/Connector_Dsub/cq_dsub.py
cadquery/FCAD_script_generator/Connector_Dsub/main_generator.py

Changed the dsub script sop it fusing the models correctly and added controls to the python script to check for correct fusion

Fixed so models gets fused correctly

---

cadquery/FCAD_script_generator/Crystal/cq_parameters.py
cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_SMD_muRata_CSTx.py
cadquery/FCAD_script_generator/Crystal/main_generator.py

Scripted 3D models of a number of resonators
3D model push
https://github.com/KiCad/kicad-packages3D/pull/585
https://github.com/easyw/kicad-3d-models-in-freecad/pull/301
Resonator_SMD-3Pin_7.2x3.0mm
http://www.farnell.com/datasheets/19296.pdf?_ga=1.247244932.122297557.1475167906
Resonator_SMD_muRata_CDSCB-2Pin_4.5x2.0mm
http://cdn-reichelt.de/documents/datenblatt/B400/SFECV-107.pdf
Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm
https://www.murata.com/en-eu/products/productdata/8801162264606/SPEC-CSTNE16M0VH3C000R0.pdf
Resonator_SMD_muRata_SFECV-3Pin_6.9x2.9mm
http://cdn-reichelt.de/documents/datenblatt/B400/SFECV-107.pdf
Resonator_SMD_muRata_SFSKA-3Pin_7.9x3.8mm
http://cdn-reichelt.de/documents/datenblatt/B400/SFECV-107.pdf
Resonator_SMD_muRata_TPSKA-3Pin_7.9x3.8mm …

Resonator smd mu rata cs tx exx g 3 pin 3.0x1.1mm

---

cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_AT310.py
cadquery/FCAD_script_generator/Crystal/main_generator.py

3D script based model of the AT310 crystal
This push adds the script for creating the crystal AT310 serie
3D model push
https://github.com/KiCad/kicad-packages3D/pull/586
https://github.com/easyw/kicad-3d-models-in-freecad/pull/302
Removal of hand made models
https://github.com/KiCad/kicad-packages3D-source/pull/233
Update of the data sheet link for the foot print
Crystal_AT310
http://www.cinetech.com.tw/upload/2011/04/20110401165201.pdf

Added 3D models for AT310 serie

---

cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_smd_type_2.py
cadquery/FCAD_script_generator/Crystal/main_generator.py

Created script based 3D models for some of micro crystals SMD crystal serie
3D model push
https://github.com/KiCad/kicad-packages3D/pull/591
https://github.com/easyw/kicad-3d-models-in-freecad/pull/306

Added micro crystals smd series of crystals

---

cadquery/FCAD_script_generator/Connector_Coaxial/cq_coaxial_amphenol.py
cadquery/FCAD_script_generator/Connector_Coaxial/cq_coaxial_samtec.py
cadquery/FCAD_script_generator/Connector_Coaxial/main_generator.py

Added union test of the step file for the coaxial connectors

Added union check on the step file

---

cadquery/FCAD_script_generator/Potentiometer_THT/README.adoc
cadquery/FCAD_script_generator/Potentiometer_THT/cq_parameters.yaml
cadquery/FCAD_script_generator/Potentiometer_THT/create_model-all.bat
cadquery/FCAD_script_generator/Potentiometer_THT/create_model-example.bat
cadquery/FCAD_script_generator/Potentiometer_THT/create_model.bat
cadquery/FCAD_script_generator/Potentiometer_THT/create_model.sh
cadquery/FCAD_script_generator/Potentiometer_THT/main_generator.py
cadquery/FCAD_script_generator/Potentiometer_THT/todo.md

Partially overtake of push
https://github.com/KiCad/kicad-packages3D/pull/527
Scripted 3D models of Bournse potentiometer serie 3005, 3006, 3009
The script checks if the models are unioned or not
Serie 3005
https://www.bourns.com/pdfs/3005.pdf
Serie 3006
https://www.bourns.com/pdfs/3006.pdf
Serie 3009
https://www.bourns.com/pdfs/3009.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/597
https://github.com/easyw/kicad-3d-models-in-freecad/pull/311

Added 3D models of Bournse potentiometer serie 3005, 3006, 3009

---

cadquery/FCAD_script_generator/Potentiometer_THT/cq_parameters.yaml
cadquery/FCAD_script_generator/Potentiometer_THT/main_generator.py

Partially overtake of push
https://github.com/KiCad/kicad-packages3D/pull/527
Scripted 3D models of Bournse potentiometer serie 3299P 3299W 3299X 3299Y 3299Z
The script checks if the models are unioned or not
Serie 3299P 3299W 3299X 3299Y 3299Z
https://www.bourns.com/pdfs/3299.pdf
3D model push
https://github.com/KiCad/kicad-packages3D/pull/598
https://github.com/easyw/kicad-3d-models-in-freecad/pull/312

Added 3D models of Bournes serie 3299P 3299W 3299X 3299Y 3299Z

---

cadquery/FCAD_script_generator/LED_SMD/cq_parameters.yaml

Rotated LED_SK6812_PLCC4 180 degree
3D model push 
https://github.com/KiCad/kicad-packages3D/pull/580

Rotated LED_SK6812_PLCC4 180 degrees

---

cadquery/FCAD_script_generator/Connector_USB/USB_C_Receptacle_Palconn_UTC16-G.py

I'm opening this PR here to continue [the discussion](https://github.com/KiCad/kicad-packages3D-source/pull/232) on how to integrate this into this repo.
I've just added the CQ1.2 compatible script, and nothing else. What should be my next step?

Added UTC16 USB-c script

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

[QFN_packages] Add DFN-4-1EP_1x1mm_P0.65mm_EP0.5x0.5mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

[QFN_packages] Add QFN-28-1EP_6x6mm_P0.65mm_EP4.8x4.8mm

---

cadquery/FCAD_script_generator/Flat_Pin_packages/main_generator.py

Change was already done with QFN_packages/main_generator.py, so do the
same in this file.

Fixed Flat_Pin_Packages/main_generator.py to use Python3

---

cadquery/FCAD_script_generator/Flat_Pin_packages/cq_parameters_diode.py

Datasheet: https://www.nxp.com/docs/en/package-information/SOD923.pdf

Added SOD-923

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/00002164B.pdf

Added QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm

---

cadquery/FCAD_script_generator/Connector_FFC-FPC/cq_models/conn_te_84952.py
cadquery/FCAD_script_generator/Connector_FFC-FPC/cq_models/conn_te_84953.py
cadquery/FCAD_script_generator/Connector_FFC-FPC/main_generator.py

Adding TE FPC-FFC connectors 84952 and 84953 series

Adding TE_84952-84953

---

cadquery/FCAD_script_generator/LED_SMD/cq_parameters.yaml

Modifed LED SMD LED_RGB_5050-6 on request from diegoherranz
https://github.com/KiCad/kicad-packages3D/pull/581

Modified model LED_RGB_5050-6

---

cadquery/FCAD_script_generator/Battery/battery_common.py
cadquery/FCAD_script_generator/Battery/main_generator.py

With these changes, main_generator.py now runs using Freecad and Python3

Fixed battery generators for Python3

---

cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/README.adoc
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/check-log.md
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/cq_parameters.yaml
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/create_model-all.bat
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/create_model-example.bat
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/create_model.bat
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/create_model.sh
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/main_generator.py
cadquery/FCAD_script_generator/RF_Antenna_Chip_SMD/todo.md

This is a script, derived from C_Chip_SMD and added polarity mark, for generating chip antennas, like:
https://www.johansontechnology.com/datasheets/2450AT18A100/2450AT18A100.pdf
https://www.johansontechnology.com/datasheets/2450AT18B100/2450AT18B100.pdf
https://www.johansontechnology.com/datasheets/2450AT43F0100/2450AT43F0100.pdf

Created script for chip antenna, derived from C_Chip_SMD, and added polarity mark.

---

cadquery/FCAD_script_generator/Fuse/README_SMD.adoc
cadquery/FCAD_script_generator/Fuse/cq_parameters_SMD.yaml
cadquery/FCAD_script_generator/Fuse/main_generator_SMD.py

Scripts are based on resistor SMD files

Added scripts to generate SMD fuses.

---

cadquery/FCAD_script_generator/Relay_THT/cq_parameters.py

Datasheet: https://omronfs.omron.com/en_US/ecb/products/pdf/en-g2rl.pdf

Added Omron G2RL relay

---

cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

Datasheet: http://www.ti.com/lit/ds/symlink/lm5161.pdf#page=34
Package drawing: http://www.ti.com/lit/ml/mpds370/mpds370.pdf
Footprint: https://github.com/pointhi/kicad-footprint-generator/pull/510

Added  HTSSOP-14-1EP_4.4x5.0mm_P0.65mm_EP3.4x5.0mm_Mask3.0x3.1mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: http://www.ti.com/lit/ds/symlink/tvs3300.pdf

Added WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: https://www.ti.com/lit/ds/symlink/tpa6132a2.pdf

Added TQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

Datasheet: https://www.vishay.com/docs/62847/siss27dn.pdf

Added parameter for epad offset and added Vishay_PowerPAK_1212-8_Single

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: https://www.ti.com/lit/ds/symlink/tpa6132a2.pdf

Added WQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

Datasheet: https://www.johansontechnology.com/datasheets/0896BM15A0001/0896BM15A0001.pdf
Depends on PR: https://github.com/easyw/kicad-3d-models-in-freecad/pull/355

 Added Johanson 0896BM15A0001 balun

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

This is needed to generate:
https://github.com/easyw/kicad-3d-models-in-freecad/pull/356

Added body material and pin indicator X,Y distance to params

---

cadquery/FCAD_script_generator/Crystal/cq_parameters_Resonator_peterman_smd.py

Datasheet: https://www.sii.co.jp/en/quartz/files/2013/03/SC-20S_Leaflet_e20151217.pdf

Added Crystal_SMD_2012-2Pin_2.0x1.2mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: https://resurgentsemi.com/wp-content/uploads/2018/09/MPR121_rev5-Resurgent.pdf

Added UQFN-20_3x3mm_P0.4mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: https://www.ti.com/lit/ds/symlink/cc430f5137.pdf

 Added VQFN-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm

---

cadquery/FCAD_script_generator/Crystal/cq_base_model.py
cadquery/FCAD_script_generator/Crystal/cq_parameters.py

cq_base_model.py copied from ../DIP_Parts

Fix Crystal scripts to run with FreeCAD 0.18 and Python 3

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: https://www.onsemi.com/pub/Collateral/LC709203F-D.PDF

Added WDFN-8-1EP_4x3mm_P0.65mm_EP2.4x1.8mm

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

Needed for example for: https://www.onsemi.com/pub/Collateral/AX-SIP-SFEU-D.PDF

Added feature for creating a matrix of exposed pads.

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: http://datasheets.avx.com/ethertronics/AVX-E_M620720.pdf

Added AVX_M620720

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

Datasheet: https://www.onsemi.com/pub/Collateral/AX-SIP-SFEU-D.PDF#page=19
Depends on: https://github.com/easyw/kicad-3d-models-in-freecad/pull/359

Added OnSemi_SIP-38-6EP-9x7mm_P0.65mm_EP0.95x0.95mm

---

cadquery/FCAD_script_generator/Buzzer_Beeper/cq_parameters.py
cadquery/FCAD_script_generator/Buzzer_Beeper/cq_parameters_PUI_AI_1440_TWT_24V_2_R.py
cadquery/FCAD_script_generator/Buzzer_Beeper/main_generator.py

Also Py3 compat fixes
https://www.shoppui.com/documents/AI-1440-TWT-24V-2-R.pdf
https://github.com/KiCad/kicad-footprints/pull/2264
https://github.com/KiCad/kicad-packages3D/pull/691

Add Buzzer_Beeper/Indicator_PUI_AI-1440-TWT-24V-2-R

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py
cadquery/FCAD_script_generator/QFN_packages/main_generator.py

plus fix Python warnings
https://pdfserv.maximintegrated.com/package_dwgs/21-0140.PDF T2055-3
https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm.kicad_mod

Add TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm

---

cadquery/FCAD_script_generator/Relay_THT/cq_parameters.py

https://gfinder.findernet.com/public/attachments/36/EN/S36EN.pdf
https://github.com/KiCad/kicad-footprints/blob/master/Relay_THT.pretty/Relay_SPDT_Finder_36.11.kicad_mod
https://github.com/KiCad/kicad-packages3D/pull/694

Add Relay_SPDT_Finder_36.11

---

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py
cadquery/FCAD_script_generator/Converter_DCDC/main_generator.py

**Based on #369**
https://www.murata.com/products/productdata/8807029669918/kdc-mee1.pdf
https://github.com/KiCad/kicad-footprints/blob/master/Converter_DCDC.pretty/Converter_DCDC_Murata_MEE1SxxxxSC_THT.kicad_mod
https://github.com/KiCad/kicad-packages3D/pull/696

Add Converter_DCDC_Murata_MEE1SxxxxSC_THT

---

cadquery/FCAD_script_generator/Converter_DCDC/cq_parameters.py
cadquery/FCAD_script_generator/Converter_DCDC/main_generator.py

https://www.murata.com/products/productdata/8807029702686/kdc-mee3.pdf
https://github.com/KiCad/kicad-footprints/blob/master/Converter_DCDC.pretty/Converter_DCDC_Murata_MEE3SxxxxSC_THT.kicad_mod
https://github.com/KiCad/kicad-packages3D/pull/695

Add Converter_DCDC_Murata_MEE3SxxxxSC_THT

---

cadquery/FCAD_script_generator/QFN_packages/cq_parameters.py

Datasheet: https://www.johansontechnology.com/datasheets/0900PC15J0013/0900PC15J0013.pdf

Added Balun Johanson 0900PC15J0013

---

cadquery/FCAD_script_generator/molex/cq_models/conn_molex_kk_41791.py
cadquery/FCAD_script_generator/molex/cq_models/conn_molex_kk_41792.py
cadquery/FCAD_script_generator/molex/cq_models/conn_molex_kk_5273.py
cadquery/FCAD_script_generator/molex/launch-cq-molex.sh
cadquery/FCAD_script_generator/molex/main_generator.py

Sorry for the 'git mess'. I fall in every pitfall ;)
Add two Molex series and minor fixes to previous PR.

Add molex series 41791 41792

---

cadquery/FCAD_script_generator/mounting_wuerth/check-log.md
cadquery/FCAD_script_generator/mounting_wuerth/wuerth_smt_spacer.py
cadquery/FCAD_script_generator/mounting_wuerth/wuerth_smt_spacer.yaml

Add M2.5 parts + update for FreeCad 0.18

Mounting Wurtz: Add M2.5 parts + update for FreeCad 0.18

---

cadquery/FCAD_script_generator/Buzzer_Beeper/cq_parameters_PUI_AI_1440_TWT_24V_2_R.py

See https://github.com/KiCad/kicad-packages3D/pull/691#issuecomment-691708559

Fix Indicator_PUI_AI_1440_TWT_24V_2_R

---

cadquery/FCAD_script_generator/Connector_Wuerth_WR-PHD/wuerth_wr_phd_bottom_entry.py

Fix position for SMD devices.
@easyw : why do you merge the pull request so fast ? You don't wait for the packages 3D to be merged in kicad library ?

Connector Wurth: WR-PHD Fix for SMD

---

cadquery/FCAD_script_generator/Connector_Wuerth_WR-PHD/wuerth_wr_phd_bottom_entry.py

Fix of script already merged before. The 3D packages are not yet in the official library bu the script should be correct now :)

Wurth WR-PHD: Fix position of pin 1 (top left)

---

cadquery/FCAD_script_generator/Connector_Wago_734/README.md
cadquery/FCAD_script_generator/Connector_Wago_734/cq_connect_wago_734.py
cadquery/FCAD_script_generator/Connector_Wago_734/main_generator.py

Vertical and horizontal type can be created.
New files:
On branch mr_connector_wago734
Changes to be committed:
new file:   cadquery/FCAD_script_generator/Connector_Wago_734/README.md
new file:   cadquery/FCAD_script_generator/Connector_Wago_734/cq_connect_wago_734.py
new file:   cadquery/FCAD_script_generator/Connector_Wago_734/main_generator.py
The scripts were tested with FreeCAD version 0.17 and 0.18
Following files con be generated (click to fold/unfold)
<details>  
<summary>Vertical connectors</summary>  
- Wago_734-132_1x02_P3.50mm_Vertical
- Wago_734-133_1x03_P3.50mm_Vertical
- Wago_734-134_1x04_P3.50mm_Vertical
- Wago_734-135_1x05_P3.50mm_Vertical
- Wago_734-136_1x06_P3.50mm_Vertical
- Wago_734-137_1x07_P3.50mm_Vertical
- Wago_734-138_1x08_P3.50mm_Vertical
- …

Added script files for generating Wago connectors type 734-xxx.
